

#' @keywords internal
#' @export
#' 
print.DoubleGap <- function(x, ...) {
  cat("Fitted Double-Gap Model\n")
  cat("\nCall:\n")
  print(x$call)
}

#' @keywords internal
#' @export
#' 
summary.DoubleGap <- function(object, ...) {
  C_M1 = summary(object$bp_model)$coefficients
  C_M2 = object$bp_gap_model$model$coef
  C_M3 = summary(object$sex_gap_model$model)$coefficients$location
  
  out = structure(class = 'summary.DoubleGap',
                  list(coef_bp_model = C_M1, 
                       coef_bp_gap_model = C_M2,
                       coef_sex_gap_model = C_M3))
  return(out)
}

#' @importFrom stats printCoefmat
#' @keywords internal
#' @export
#' 
print.summary.DoubleGap <- function(x, ...){
  cat("\nCoefficients Double-Gap Model:\n")
  cat("\nM1: Best-Practice Life Expectancy Model\n")
  printCoefmat(x$coef_bp_model, signif.legend = FALSE)
  cat("\nM2: Best-Practice Gap Model\n")
  print(x$coef_bp_gap_model)
  cat("\nM3: Sex-Gap Model\n")
  printCoefmat(x$coef_sex_gap_model)
}


#' @keywords internal
#' @export
#' 
print.predict.DoubleGap <- function(x, ...) {
  cat("Predicted values generated by the Double-Gap Model\n")
  cat(paste0("Country: ", x$pred.values$country[1], "\n"))
  cat(paste0("Age (x): ", x$pred.values$Age[1], "\n\n"))
  print(x$pred.values[, c(-1, -3)])
}
