

#' @keywords internal
#' @export
#' 
print.DoubleGap <- function(x, ...) {
  cat("Double-Gap Model fit\n")
  cat('\nCountry: ', x$data$country)
  cat('\nAge (x): ', x$data$age)
  cat('\nYears in fit: ', paste(range(x$data$years), collapse = ' - '), '\n')
}

#' @keywords internal
#' @export
#' 
summary.DoubleGap <- function(object, ...) {
  C_M1 <- summary(object$model.parts$bp_model)$coefficients
  C_M2 <- object$model.parts$bp_gap_model$model$coef
  C_M3 <- summary(object$model.parts$sex_gap_model$model)$coefficients[[1]]
  coef <- coef(object)
  out  <- structure(class = 'summary.DoubleGap',
                    list(coef_bp_model = C_M1, 
                         coef_bp_gap_model = C_M2,
                         coef_sex_gap_model = C_M3,
                         coef = coef))
  return(out)
}


#' @keywords internal
#' @export
#' 
print.summary.DoubleGap <- function(x, ...){
  cat("\nCoefficients Double-Gap Model:\n")
  cat("\nM1: Best-Practice Life Expectancy Model\n")
  printCoefmat(x$coef_bp_model, signif.legend = FALSE)
  cat("\nM2: Best-Practice Gap Model (ARIMA)\n")
  print(x$coef_bp_gap_model)
  cat("\nM3: Sex-Gap Model\n")
  printCoefmat(x$coef_sex_gap_model)
  cat("\ntau =", paste0(x$coef$sex_gap_model['tau']))
  cat(" | A =", paste0(x$coef$sex_gap_model['A']))
  cat(" | L =", round(x$coef$sex_gap_bounds['L'], 2))
  cat(" | U =", round(x$coef$sex_gap_bounds['U'], 2))
}


#' @keywords internal
#' @export
#' 
print.predict.DoubleGap <- function(x, ...) {
  cat("Predicted values generated by the Double-Gap Model\n")
  cat(paste0("Country: ", x$pred.values$country[1], "\n"))
  cat(paste0("Age (x): ", x$pred.values$Age[1], "\n\n"))
  print(x$pred.values[, c(-1, -3)])
}


#' Generic Plot Function for Class predict.DoubleGap
#' 
#' @param x An object of class \code{\link{predict.DoubleGap}}
#' @param show.legend Logical. Indicate whether to display the legend or not. Default: TRUE.
#' @param ylim Numeric vectors of length 2, giving the x and y coordinates ranges.
#' @param asp Numeric, giving the aspect ratio y/x.
#' @param xlab A title for the x axis: see \code{\link{title}}.
#' @param ylab A title for the y axis: see \code{\link{title}}.
#' @param ... Further graphical parameters as in \code{\link{par}}. 
#' @export
plot.predict.DoubleGap <- function(x, show.legend = TRUE, ylim = NULL, 
                                   asp = 1.8, xlab = "\nYear", 
                                   ylab = "\nLife Expectancy Level", ...){
  # Observed & fitted data
  fit    <- x$input$object
  bp_exT <- fit$fitted.values$bp_ex # Best-practice trend
  bp_exH <- fit$observed.values$bp_ex # Observed record ex
  exfH   <- fit$observed.values$exf
  exmH   <- fit$observed.values$exm
  hyr    <- fit$data$years # years
  
  # Forecast values
  bp_exF <- x$pred.values$bp_ex
  cif <- x$pred.intervals$exf # confidence intervals females
  cim <- x$pred.intervals$exm # confidence intervals males
  fyr <- x$pred.values$Year #years
  yr  <- c(hyr, fyr) # all years
  
  # Plot
  if (is.null(ylim)) ylim <- trunc(range(bp_exH) * c(.9, 1.1))
  breaks_x <- c(min(hyr), round(mean(range(hyr)), -1), max(hyr), max(fyr))
  breaks_y <- seq(ylim[1], ylim[2], by = 3)
  
  par(cex.lab = 1.6, cex.axis = 1.6)
  plot(hyr, bp_exH, type = "n", axes = F, asp = asp, ylim = ylim, 
       xlim = range(yr), xlab = xlab, ylab = ylab, ...)
  axis(1, at = breaks_x, lwd = 3, col = 1, cex.axis = 1.5)
  axis(2, at = breaks_y, lwd = 3, col = 1, cex.axis = 1.5)
  abline(v = seq(min(hyr), max(fyr), by = 10), col = "grey80", lty = 3)
  abline(h = seq(ylim[1], ylim[2], by = 1.5), col = "grey80", lty = 3)
  
  polygon(c(rev(hyr), hyr), c(rev(bp_exT), exfH), col = 'mistyrose', 
          border = NA, density = 100, lty = 1, angle = 90)
  polygon(c(rev(hyr), hyr), c(rev(exfH), exmH), col = 'lightcyan1', 
          border = NA, density = 100, lty = 1, angle = 90 )
  
  lines(hyr, bp_exT, lwd = 2, col = 'grey70')
  lines(hyr, exfH, lwd = 2, col = 1, lty = 1)
  lines(hyr, exmH, lwd = 2, col = 1, lty = 1)
  
  polygon(c(rev(fyr), fyr), c(rev(cim[,2]), cim[,5]), col = '#dadaeb', density = 100, angle = 90)
  polygon(c(rev(fyr), fyr), c(rev(cif[,2]), cif[,5]), col = '#dadaeb', density = 100, angle = 90)
  polygon(c(rev(fyr), fyr), c(rev(cim[,3]), cim[,4]), col = '#bcbddc', density = 100, angle = 90)
  polygon(c(rev(fyr), fyr), c(rev(cif[,3]), cif[,4]), col = '#bcbddc', density = 100, angle = 90)
  
  lines(fyr, bp_exF, lwd = 2, col = "grey70", lty = 1)
  points(hyr, bp_exH, pch = 16, cex = 1.2, col = 1) 
  lines(fyr, cif[,1], lwd = 2, col = 4, lty = 2)
  lines(fyr, cim[,1], lwd = 2, col = 4, lty = 2)
  
  abline(v = max(hyr) + 0.3, lty = 2)
  text(mean(hyr), ylim[1], "Fitted", cex = 1.7)
  text(mean(fyr), ylim[1], "Forecast", cex = 1.7)
  
  if (show.legend) {
    l_names <- c("Record Life Expectancy", 
                 "Best-Practice Trend",
                 "Obs. F & M Life Expectancy", 
                 "DG Forecast", 
                 "BP-gap (D)", 
                 "Sex-gap (G)",
                 "CI: 80% level", "CI: 95% level")
    legend('topleft', legend = l_names, bty = "n",
           lty = c(NA, 1, 1, 2, NA, NA, NA, NA), 
           pch = c(16, NA, NA, NA, 15, 15, 15, 15),
           col = c(1, "grey70", 1, 4, "mistyrose", "lightcyan1", "#bcbddc", "#dadaeb"), 
           cex = 1, pt.cex = 2.0, lwd = 3)
  }
}



